contact_links:
  - name: Join nf-core
    url: https://nf-co.re/join
    about: Please join the nf-core community here
  - name: "Slack #pathogenseq channel"
    url: https://nfcore.slack.com/channels/pathogenseq
    about: Discussion about the nf-core/pathogenseq pipeline
